use super::*;
use crate::*;
use std::fmt::Debug;

/// Decode original-native artifacts, re-encode through both the explicit V1
/// writer and the unchanged native writer. The expected bytes were captured
/// before this increment, never generated by the implementation under test.
fn original<T: V1 + Serialize + PartialEq + Debug>(bytes: &[u8]) -> T {
    let (Value(value), rest) = postcard::take_from_bytes::<Value<T>>(bytes).unwrap();
    assert!(rest.is_empty());
    assert_eq!(postcard::to_stdvec(&Ref(&value)).unwrap(), bytes);
    assert_eq!(postcard::to_stdvec(&value).unwrap(), bytes);
    if !bytes.is_empty() {
        assert!(postcard::take_from_bytes::<Value<T>>(&bytes[..bytes.len() - 1]).is_err());
    }
    value
}

#[test]
fn original_output_corpus_preserves_every_fact_effect_and_domain_outcome() {
    let facts = original::<Vec<DeltaFact>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/delta-facts.rows"
    ));
    assert_eq!(facts.len(), 13);
    let deltas = original::<Vec<Delta>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/deltas.rows"
    ));
    assert_eq!(
        deltas.iter().map(|delta| &delta.fact).collect::<Vec<_>>(),
        facts.iter().collect::<Vec<_>>()
    );
    assert_eq!(
        original::<Vec<EffectIntent>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/effects.rows"
        ))
        .len(),
        7
    );
    assert_eq!(
        original::<Vec<InformReason>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/inform-reasons.rows"
        ))
        .len(),
        6
    );
    assert_eq!(
        original::<Vec<DomainOutcome>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/domain-outcomes.rows"
        ))
        .len(),
        52
    );
    assert_eq!(
        original::<Vec<CommandResult>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/command-results.rows"
        ))
        .len(),
        14
    );
}

#[test]
fn original_cursor_corpus_preserves_empty_noncanonical_and_all_mode_rows() {
    let records = original::<Vec<CursorRecordSnapshot>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/cursor-records.rows"
    ));
    assert_eq!(records.len(), 81);
    assert!(
        records
            .iter()
            .any(|row| matches!(&row.filter, CursorFilterSnapshot::Claims(ids) if ids.is_empty()))
    );
    // Historic codec rows remain readable even when current admission demands
    // canonical sorted unique filters. No normalization belongs in this codec.
    assert!(records.iter().any(|row| matches!(&row.filter, CursorFilterSnapshot::Claims(ids) if ids.windows(2).any(|pair| pair[0] > pair[1]))));
    let receipts = original::<Vec<CursorMutationReceipt>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/cursor-receipts.rows"
    ));
    assert_eq!(receipts.len(), 82);
    assert!(receipts[0].record.is_none());
}

#[test]
fn original_managed_receipts_and_hashes_preserve_all_domain_cursor_and_seal_outcomes() {
    assert_eq!(
        original::<Vec<ManagedRequestFamily>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/families.rows"
        )),
        [ManagedRequestFamily::Domain, ManagedRequestFamily::Cursor]
    );
    assert_eq!(
        original::<Vec<ManagedReceiptOutcome>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/managed-outcomes.rows"
        ))
        .len(),
        98
    );
    let receipts = original::<Vec<ManagedReceipt>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/managed-receipts.rows"
    ));
    let hashes = original::<Vec<ContentHash>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/managed-receipt-hashes.rows"
    ));
    assert_eq!(receipts.len(), 98);
    assert_eq!(receipts.len(), hashes.len());
    for (receipt, expected) in receipts.iter().zip(hashes) {
        assert_eq!(receipt.content_hash().unwrap(), expected);
    }
    assert_eq!(
        original::<Vec<ManagedReceiptAck>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/managed-acks.rows"
        ))
        .len(),
        receipts.len()
    );
}

#[test]
fn original_stream_controls_states_receipts_and_queries_keep_their_fixed_order() {
    assert_eq!(
        original::<Vec<RequestStreamCommand>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/stream-commands.rows"
        ))
        .len(),
        8
    );
    let inputs = original::<Vec<RequestStreamControlInput>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/stream-inputs.rows"
    ));
    let hashes = original::<Vec<ContentHash>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/stream-intent-hashes.rows"
    ));
    assert_eq!(inputs.len(), hashes.len());
    for (input, expected) in inputs.iter().zip(hashes) {
        assert_eq!(input.intent_hash().unwrap(), expected);
        let mut independent_id = input.clone();
        independent_id.id = RequestId::from_u128(u128::MAX);
        assert_eq!(independent_id.intent_hash().unwrap(), expected);
    }
    assert_eq!(
        original::<Vec<RequestStreamState>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/stream-states.rows"
        ))
        .len(),
        4
    );
    assert_eq!(
        original::<Vec<RequestStreamControlOutcome>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/stream-outcomes.rows"
        ))
        .len(),
        104
    );
    assert_eq!(
        original::<Vec<RequestStreamControlReceipt>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/stream-receipts.rows"
        ))
        .len(),
        104
    );
    assert_eq!(
        original::<Vec<RequestStreamQuery>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/stream-queries.rows"
        ))
        .len(),
        2
    );
    assert_eq!(
        original::<Vec<ManagedReceiptResolution>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/managed-resolutions.rows"
        ))
        .len(),
        101
    );
    assert_eq!(
        original::<Vec<RequestStreamReadResult>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/stream-read-results.rows"
        ))
        .len(),
        105
    );
    assert_eq!(
        original::<Vec<RequestStreamRead>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/stream-reads.rows"
        ))
        .len(),
        105
    );
    assert_eq!(
        original::<Vec<ManagedFormatSupport>>(include_bytes!(
            "../../fixtures/durable-v1-outputs/managed-format-support.rows"
        ))
        .len(),
        2
    );
}

#[test]
fn new_critical_enum_ordinals_are_not_silently_admitted_as_v1() {
    macro_rules! unknown {
        ($($ty:ty => $tag:literal),+ $(,)?) => { $(assert!(postcard::from_bytes::<Value<$ty>>(&[$tag]).is_err(), stringify!($ty));)+ };
    }
    unknown!(DeltaFact=>11, EffectIntent=>5, DomainOutcome=>3, InformReason=>6,
        ManagedRequestFamily=>2, ManagedReceiptOutcome=>3, RequestStreamCommand=>4,
        RequestStreamState=>2, RequestStreamControlOutcome=>4, RequestStreamQuery=>2,
        ManagedReceiptResolution=>4, RequestStreamReadResult=>2,
        CursorPositionOffsetSnapshot=>2, CursorFilterSnapshot=>2, CursorModeSnapshot=>4,
        CursorResyncReason=>5);
}

#[test]
fn borrowed_sequences_boxes_and_raw_hash_keep_the_original_bytes() {
    let rows = original::<Vec<Delta>>(include_bytes!(
        "../../fixtures/durable-v1-outputs/deltas.rows"
    ));
    let original = postcard::to_stdvec(&rows).unwrap();
    assert_eq!(postcard::to_stdvec(&Sequence(&rows)).unwrap(), original);
    assert_eq!(
        hash(&rows).unwrap(),
        ContentHash(*blake3::hash(&original).as_bytes())
    );
    let bytes: Vec<u8> = (0..8197).map(|n| (n % 251) as u8).collect();
    assert_eq!(
        postcard::to_stdvec(&Sequence(&bytes)).unwrap(),
        postcard::to_stdvec(&bytes).unwrap()
    );
    let boxed = Box::new(rows);
    assert_eq!(postcard::to_stdvec(&Ref(&boxed)).unwrap(), original);
    assert_eq!(
        postcard::from_bytes::<Value<Box<Vec<Delta>>>>(&original)
            .unwrap()
            .0,
        boxed
    );
    let huge = postcard::to_stdvec(&u64::MAX).unwrap();
    assert!(postcard::from_bytes::<Value<Vec<Delta>>>(&huge).is_err());
    assert!(postcard::from_bytes::<Value<Box<ManagedReceipt>>>(&[]).is_err());
}
