apiVersion: v1
kind: Service
metadata:
  name: focal
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: focal
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: focal
  ports:
    - name: peer
      port: {{ .Values.port }}
      targetPort: peer
      protocol: UDP
