use super::{
    Capability, InputKind, OperationDescriptor, ResultKind, RetryIdentity, Surface, WireProfile,
};
use crate::input::MAX_INPUT_BYTES;

/// Local physical-node administration. Root changes journal `a1:` references, application changes `r1:` references; invitations come from the founder signer.
const CLUSTER_NODE_IDENTITY: OperationDescriptor = OperationDescriptor {
    name: "cluster.node.identity",
    version: 1,
    description: "Read the authenticated physical owner's immutable identity. No participant or administration authority is transferred.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster node identity"),
    input: InputKind::Literal(r#"{"type":"object","additionalProperties":false,"properties":{}}"#),
    family: None,
};
const CLUSTER_NODE_HEALTH: OperationDescriptor = OperationDescriptor {
    name: "cluster.node.health",
    version: 1,
    description: "Observe local root and fleet owner progress. This diagnostic is not a quorum, placement or complete service health guarantee.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster node health"),
    input: InputKind::Literal(r#"{"type":"object","additionalProperties":false,"properties":{}}"#),
    family: None,
};
const CLUSTER_NODE_CONFIG: OperationDescriptor = OperationDescriptor {
    name: "cluster.node.config",
    version: 1,
    description: "Read the running physical node's validated saved listener and root namespace configuration. No desired placement policy or achieved guarantee is inferred.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster node config"),
    input: InputKind::Literal(r#"{"type":"object","additionalProperties":false,"properties":{}}"#),
    family: None,
};
const CLUSTER_REPLICAS_DIAGNOSTICS: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.diagnostics",
    version: 1,
    description: "Observe an installed application owner's commit/applied prefix, pending checkpoint and immutable decoder floor. No checkpoint, activation or upgrade is initiated.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas diagnostics"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"properties":{"session":{"type":"string","pattern":"^[0-9a-fA-F]{32}$"}}}"#,
    ),
    family: None,
};
const CLUSTER_RETENTION_SHOW: OperationDescriptor = OperationDescriptor {
    name: "cluster.retention.show",
    version: 1,
    description: "A native session's retention floor (the published prefix, what registered consumers still need, what the archive reports holding, the least of them and what holds it there) and its archive counts (families retired, a retirement in flight). No reclamation is initiated.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster retention show"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"properties":{"session":{"type":"string","pattern":"^[0-9a-fA-F]{32}$"}}}"#,
    ),
    family: None,
};
const CLUSTER_ARCHIVE_SHOW: OperationDescriptor = OperationDescriptor {
    name: "cluster.archive.show",
    version: 1,
    description: "The continuation a retired claim left in a native session's core and its archive bundle as this node holds it: the bundle's root and length, whether it verified structurally, its root and members, rows by family, and the required copies holding a receipt. Absent continuation reads as null.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster archive show"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["claim"],"properties":{"session":{"type":"string","pattern":"^[0-9a-fA-F]{32}$"},"claim":{"type":"string","pattern":"^[0-9a-fA-F]{32}$"}}}"#,
    ),
    family: None,
};
const CLUSTER_GC_SHOW: OperationDescriptor = OperationDescriptor {
    name: "cluster.gc.show",
    version: 1,
    description: "The collector's state on this node: its settings (interval, grace, quarantine, terminal fence, records kept, mark bound), whether a pass is in progress, how many completed, and the last pass's report (roots protected, opaque domains, unreadable bundles, what the content store expired, quarantined, deferred and deleted, what the seed sweeps removed). No collection is initiated.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster gc show"),
    input: InputKind::Literal(r#"{"type":"object","additionalProperties":false,"properties":{}}"#),
    family: None,
};
const CLUSTER_BACKUP_CREATE: OperationDescriptor = OperationDescriptor {
    name: "cluster.backup.create",
    version: 1,
    description: "Write a coherent backup of a hosted native session at a declared prefix into a new directory on this node: the session envelope its replica installed durably (a checkpoint is taken and fsynced first), the chunks of a seeded Core root, the exact authenticated tree of every content object the prefix's rows and archive bundles name, and a manifest written last. A directory that already holds a backup is refused; a killed write leaves no manifest and therefore no backup.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster backup create"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["output"],"properties":{"tenant":{"type":"string","pattern":"^[0-9a-fA-F]{32}$"},"session":{"type":"string","pattern":"^[0-9a-fA-F]{32}$"},"output":{"type":"string","minLength":1}}}"#,
    ),
    family: None,
};
const CLUSTER_BACKUP_VERIFY: OperationDescriptor = OperationDescriptor {
    name: "cluster.backup.verify",
    version: 1,
    description: "Verify a backup directory without writing: the manifest's digest and schema, the envelope's hash, every seed chunk and every object's manifest and chunks, then rebuild the envelope against the backup's own content and compare what it names with what the manifest lists; report whether this binary carries the decoder the backup's log promised. Problems are listed, not hidden.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster backup verify"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["input"],"properties":{"input":{"type":"string","minLength":1}}}"#,
    ),
    family: None,
};
const CLUSTER_STORAGE_SHOW: OperationDescriptor = OperationDescriptor {
    name: "cluster.storage.show",
    version: 1,
    description: "The storage view of this node: the volume envelope every durable owner promises its bytes to (free bytes at the last sample, bytes outstanding by kind, the headroom never spent and the completion reserve), uploads staged, the archive agent's settings and progress, the collector's settings, and for every hosted native session whether this node is its authority, the log kept beyond its checkpoint and its retention floor with what holds it there. No reclamation is initiated.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster storage show"),
    input: InputKind::Literal(r#"{"type":"object","additionalProperties":false,"properties":{}}"#),
    family: None,
};
const CLUSTER_RESTORE: OperationDescriptor = OperationDescriptor {
    name: "cluster.restore",
    version: 1,
    description: "Restore a native session from a verified backup directory onto this node (26 §6): the backup is verified first, its objects are imported into this node's content store and its seed chunks into the session's seed store, its envelope is rewritten for the incarnation the restore takes, a fresh log begins from it, and the session is hosted and registered with the directory as founded here. The old incarnation continues only when the backup came from this cluster and every other member of its membership is revoked; otherwise the restore is a recovery incarnation under a new log group and genesis, which `new_incarnation` must acknowledge. A session this cluster's directory already holds, or this node already hosts, is refused. The tenant must be served by this cluster.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster restore"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["input"],"properties":{"input":{"type":"string","minLength":1},"new_incarnation":{"type":"boolean"}}}"#,
    ),
    family: None,
};
const CLUSTER_GC_RESTORE: OperationDescriptor = OperationDescriptor {
    name: "cluster.gc.restore",
    version: 1,
    description: "Bring a quarantined content object back into this node's store by its domain and root, with every chunk of it still quarantined, while its round has not expired. Exact on retry: an object already back, or one no round holds, reads as not restored.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster gc restore"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["domain","root"],"properties":{"domain":{"type":"string","pattern":"^[0-9a-fA-F]{32}$"},"root":{"type":"string","pattern":"^[0-9a-fA-F]{64}$"}}}"#,
    ),
    family: None,
};
const CLUSTER_INVITE: OperationDescriptor = OperationDescriptor {
    name: "cluster.invite",
    version: 1,
    description: "Create or recover the exact named private Node invitation through the local founder signer. This grants enrollment only, not voting or placement.",
    capability: Capability::FounderNode,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster invite"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["node","output"],"properties":{"node":{"type":"string","minLength":1,"maxLength":63,"pattern":"^[A-Za-z0-9_.-]+$"},"output":{"type":"string","minLength":1,"maxLength":4096}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_TRANSFER: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.transfer",
    version: 1,
    description: "Initiate application-group leadership transfer under an exact owner-checked configuration fence. Success does not assert election completion.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas transfer"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["node"],"properties":{"session":{"type":"string","pattern":"^[0-9a-f]{32}$"},"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_LIST: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.list",
    version: 1,
    description: "Observe a bounded live page of locally installed application replicas. Management sequence is process-local; this is not a placement or quorum snapshot.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas list"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":[],"properties":{"after":{"type":"string","pattern":"^[0-9a-f]{32}$"},"limit":{"type":"integer","minimum":1,"maximum":64,"default":32}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_SHOW: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.show",
    version: 1,
    description: "Quorum-read an installed application replica's committed configuration. Omitting session selects the physical node's original application ledger.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas show"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":[],"properties":{"session":{"type":"string","pattern":"^[0-9a-f]{32}$"}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_ADD_LEARNER: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.add_learner",
    version: 1,
    description: "Journal exact application-group learner admission, preserving managed decoder-floor and candidate checks. This does not install a remote replica or activate durability.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas membership add-learner"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["node"],"properties":{"session":{"type":"string","pattern":"^[0-9a-f]{32}$"},"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_PROMOTE: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.promote",
    version: 1,
    description: "Journal application-group promotion; commit requires actual catch-up and existing decoder compatibility guards.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas membership promote"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["node"],"properties":{"session":{"type":"string","pattern":"^[0-9a-f]{32}$"},"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_REMOVE: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.remove",
    version: 1,
    description: "Journal exact application-group removal; this does not drain or reassign placement.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas membership remove"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["node"],"properties":{"session":{"type":"string","pattern":"^[0-9a-f]{32}$"},"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_LEAVE_JOINT: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.leave_joint",
    version: 1,
    description: "Commit exit from an existing joint application configuration.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas membership leave-joint"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":[],"properties":{"session":{"type":"string","pattern":"^[0-9a-f]{32}$"},"expected_configuration_index":{"type":"integer","minimum":0}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_REQUEST_INSPECT: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.request.inspect",
    version: 1,
    description: "Read the retained local r1 operation reference and known exact membership receipt.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas request inspect"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":[],"properties":{}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_REQUEST_RETRY: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.request.retry",
    version: 1,
    description: "Retry only the retained exact r1 membership request. No new intent or replacement replica is created.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::ReplicaR1,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas request retry"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["operation_id"],"properties":{"operation_id":{"type":"string","pattern":"^r1:[0-9a-f]{16}:[0-9a-f]{32}$","minLength":52,"maxLength":52}}}"#,
    ),
    family: None,
};
const CLUSTER_REPLICAS_REQUEST_RECONCILE: OperationDescriptor = OperationDescriptor {
    name: "cluster.replicas.request.reconcile",
    version: 1,
    description: "Recover the exact latest membership receipt or preserve FencedOutcomeUnknown when a newer configuration makes the old request permanently inadmissible.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::ReplicaR1,
    surface: Surface::Administration,
    cli_path: Some("cluster replicas request reconcile"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["operation_id"],"properties":{"operation_id":{"type":"string","pattern":"^r1:[0-9a-f]{16}:[0-9a-f]{32}$","minLength":52,"maxLength":52}}}"#,
    ),
    family: None,
};
const CLUSTER_STATUS: OperationDescriptor = OperationDescriptor {
    name: "cluster.status",
    version: 1,
    description: "Quorum-read the local root-group leader and voters. A contact is not membership or placement.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster status"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_MEMBERSHIP_SHOW: OperationDescriptor = OperationDescriptor {
    name: "cluster.membership.show",
    version: 1,
    description: "Read the committed exact root configuration and its applied fence.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster membership show"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_NODES_LIST: OperationDescriptor = OperationDescriptor {
    name: "cluster.nodes.list",
    version: 1,
    description: "Read committed node contact announcements. This does not assert active credentials, voter membership, or achieved durability.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster nodes list"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_NODES_DRAIN: OperationDescriptor = OperationDescriptor {
    name: "cluster.nodes.drain",
    version: 1,
    description: "Stop placing sessions on a node: the root re-issues its grant ineligible at the next generation, the controller heals every placement that named it and retires its copies. The founder is never drained. Exact on retry; a node already drained commits nothing.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster nodes drain"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1}},"required":["node"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_NODES_UNDRAIN: OperationDescriptor = OperationDescriptor {
    name: "cluster.nodes.undrain",
    version: 1,
    description: "Consider a drained node for placement again: its grant is re-issued eligible at the next generation. Exact on retry; a node already eligible commits nothing.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster nodes undrain"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1}},"required":["node"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_NODES_REMOVE: OperationDescriptor = OperationDescriptor {
    name: "cluster.nodes.remove",
    version: 1,
    description: "Remove a drained node no session names any more: its root-group membership when it has one, then the credential its invitation issued. Refused while the node is eligible or still holds copies. Each step is an exact journaled request, so a repeated call resumes.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster nodes remove"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1}},"required":["node"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_NODES_REPLACE: OperationDescriptor = OperationDescriptor {
    name: "cluster.nodes.replace",
    version: 1,
    description: "Drain a node once its replacement is enrolled, alive, eligible and reporting, so the healed placements have a host to move to; the planner chooses among every eligible node. Exact on retry.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster nodes replace"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1},"replacement":{"type":"integer","minimum":1}},"required":["node","replacement"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_MEMBERSHIP_ADD_LEARNER: OperationDescriptor = OperationDescriptor {
    name: "cluster.membership.add_learner",
    version: 1,
    description: "Journal and commit a root learner admission. On a lost response use cluster.request.inspect and retry that exact reference.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster membership add-learner"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}},"required":["node"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_MEMBERSHIP_PROMOTE: OperationDescriptor = OperationDescriptor {
    name: "cluster.membership.promote",
    version: 1,
    description: "Commit promotion only after existing consensus catch-up and configuration checks. Lost outcomes remain journaled.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster membership promote"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}},"required":["node"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_MEMBERSHIP_REMOVE: OperationDescriptor = OperationDescriptor {
    name: "cluster.membership.remove",
    version: 1,
    description: "Commit root-group member removal under its exact configuration. This is not a data-placement drain.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster membership remove"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}},"required":["node"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_MEMBERSHIP_LEAVE_JOINT: OperationDescriptor = OperationDescriptor {
    name: "cluster.membership.leave_joint",
    version: 1,
    description: "Commit completion of an existing joint root configuration.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster membership leave-joint"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"expected_configuration_index":{"type":"integer","minimum":0}},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_LEADER_TRANSFER: OperationDescriptor = OperationDescriptor {
    name: "cluster.leader.transfer",
    version: 1,
    description: "Initiate a transfer to an eligible root voter. Success is initiation, not a committed or observed leadership change.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster leader transfer"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"node":{"type":"integer","minimum":1},"expected_configuration_index":{"type":"integer","minimum":0}},"required":["node"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_REQUEST_INSPECT: OperationDescriptor = OperationDescriptor {
    name: "cluster.request.inspect",
    version: 1,
    description: "Read the latest local admin journal reference and committed receipt, if known. No request is sent.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster request inspect"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_REQUEST_RECONCILE: OperationDescriptor = OperationDescriptor {
    name: "cluster.request.reconcile",
    version: 1,
    description: "Persist a known receipt, or a same-prefix proof that an absent request precondition was superseded. Absence alone never releases an unknown intent.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::AdminA1,
    surface: Surface::Administration,
    cli_path: Some("cluster request reconcile"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"operation_id":{"type":"string","pattern":"^a1:[0-9a-f]{16}:[0-9a-f]{16}$","minLength":36,"maxLength":36}},"required":["operation_id"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_REQUEST_RETRY: OperationDescriptor = OperationDescriptor {
    name: "cluster.request.retry",
    version: 1,
    description: "Retry only the exact retained latest admin request. An older reference never creates new work.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::AdminA1,
    surface: Surface::Administration,
    cli_path: Some("cluster request retry"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"operation_id":{"type":"string","pattern":"^a1:[0-9a-f]{16}:[0-9a-f]{16}$","minLength":36,"maxLength":36}},"required":["operation_id"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_INVITATIONS_LIST: OperationDescriptor = OperationDescriptor {
    name: "cluster.invitations.list",
    version: 1,
    description: "Read redacted committed invitation and issued-credential metadata, never secrets. Page with expected_revision to reject a changing registry.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster invitations list"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"after":{"type":"string","pattern":"^[0-9a-f]{32}$","minLength":32,"maxLength":32},"limit":{"type":"integer","minimum":1,"maximum":64,"default":32},"expected_revision":{"type":"integer","minimum":0}},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_INVITATIONS_GET: OperationDescriptor = OperationDescriptor {
    name: "cluster.invitations.get",
    version: 1,
    description: "Read redacted committed invitation and issued-credential metadata, never secrets. Page with expected_revision to reject a changing registry.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster invitations get"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"id":{"type":"string","pattern":"^[0-9a-f]{32}$","minLength":32,"maxLength":32}},"required":["id"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_CREDENTIALS_GET: OperationDescriptor = OperationDescriptor {
    name: "cluster.credentials.get",
    version: 1,
    description: "Read redacted committed invitation and issued-credential metadata, never secrets. Page with expected_revision to reject a changing registry.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster credentials get"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"id":{"type":"string","pattern":"^[0-9a-f]{32}$","minLength":32,"maxLength":32}},"required":["id"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_INVITATIONS_REVOKE: OperationDescriptor = OperationDescriptor {
    name: "cluster.invitations.revoke",
    version: 1,
    description: "Journal and commit revocation of this invitation and any credential it issued. This does not drain data or remove consensus membership. Lost replies use cluster.request.inspect/retry.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster invitations revoke"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"id":{"type":"string","pattern":"^[0-9a-f]{32}$","minLength":32,"maxLength":32},"expected_revision":{"type":"integer","minimum":0}},"required":["id"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_CREDENTIALS_REVOKE: OperationDescriptor = OperationDescriptor {
    name: "cluster.credentials.revoke",
    version: 1,
    description: "Journal and commit revocation of this invitation and any credential it issued. This does not drain data or remove consensus membership. Lost replies use cluster.request.inspect/retry.",
    capability: Capability::Node,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster credentials revoke"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"id":{"type":"string","pattern":"^[0-9a-f]{32}$","minLength":32,"maxLength":32},"expected_revision":{"type":"integer","minimum":0}},"required":["id"],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_CLIENT_INVITE: OperationDescriptor = OperationDescriptor {
    name: "cluster.client.invite",
    version: 1,
    description: "Create or recover an exact named Client-role invitation and atomically write its private file without overwriting another invitation. No secret appears in the result; the client is not a node or Runtime.",
    capability: Capability::FounderNode,
    mutation: true,
    destructive: true,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster client invite"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["name","output"],"properties":{"name":{"type":"string","minLength":1,"maxLength":63,"pattern":"^[a-zA-Z0-9_.-]+$"},"output":{"type":"string","minLength":1,"maxLength":4096}}}"#,
    ),
    family: None,
};
const CLUSTER_CREDENTIALS_RENEW: OperationDescriptor = OperationDescriptor {
    name: "cluster.credentials.renew",
    version: 1,
    description: "Renew this node's own credential now: the same key under a fresh certificate and lifetime, installed and presented on every path before the reply. The founder's identity is its bootstrap authority's certificate and is not renewed. A retry after an interrupted renewal converges on the committed one.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Fresh,
    surface: Surface::Administration,
    cli_path: Some("cluster credentials renew"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_PLACEMENT: OperationDescriptor = OperationDescriptor {
    name: "cluster.placement",
    version: 1,
    description: "Every directory partition this node acts on as its placement agent last observed it: nodes with their enrollment, liveness and load, and each session's placement, epochs, desired and achieved guarantee, pending plan progress and what blocks it. A read of committed directory facts, never a change.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster placement"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_PLAN: OperationDescriptor = OperationDescriptor {
    name: "cluster.plan",
    version: 1,
    description: "The bounded next actions the placement controller would take from the committed directory: begin, install, add and promote learners, cut over, activate, drain, retire, replan, split or merge. An explanation of what the controller does unattended, never a change.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster plan"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_TENANTS_ADMIT: OperationDescriptor = OperationDescriptor {
    name: "cluster.tenants.admit",
    version: 1,
    description: "Admit a tenant the cluster serves, as a committed enrollment fact under the founder's authority: every node's grants and local socket then name it, without a restart. Retrying an admitted tenant reads as done. Tenants are admitted, never removed.",
    capability: Capability::FounderNode,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster tenants admit"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["tenant"],"properties":{"tenant":{"type":"string","minLength":32,"maxLength":32,"pattern":"^[0-9a-f]{32}$"}}}"#,
    ),
    family: None,
};
const CLUSTER_TENANTS_LIST: OperationDescriptor = OperationDescriptor {
    name: "cluster.tenants.list",
    version: 1,
    description: "The tenants the cluster serves: the founder's own and every admitted one, at the committed enrollment revision.",
    capability: Capability::Node,
    mutation: false,
    destructive: false,
    result_kind: ResultKind::Read,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster tenants list"),
    input: InputKind::Literal(
        r#"{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{},"required":[],"additionalProperties":false}"#,
    ),
    family: None,
};
const CLUSTER_SESSIONS_CREATE: OperationDescriptor = OperationDescriptor {
    name: "cluster.sessions.create",
    version: 1,
    description: "Create an application session on this node for the founder's tenant or an admitted one. The session identity derives from the cluster, tenant and name, so the same name is the same session and a retry is exact; the reply names the ledger, its log group and the node. The session is registered with the directory and placed under the deployment policy like the founder's.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster sessions create"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["tenant","name"],"properties":{"tenant":{"type":"string","minLength":32,"maxLength":32,"pattern":"^[0-9a-f]{32}$"},"name":{"type":"string","minLength":1,"maxLength":63,"pattern":"^[A-Za-z0-9_.-]+$"}}}"#,
    ),
    family: None,
};
const CLUSTER_SESSIONS_PLAN: OperationDescriptor = OperationDescriptor {
    name: "cluster.sessions.plan",
    version: 2,
    description: "Plan a session's placement under a requested durability (survive node, zone or region with up to N failures): the planner picks live, eligible nodes from the committed directory and the controller executes the plan unattended (install, catch up, promote, cut over, activate). The reply names the plan: planned, pending when one is already under way, or satisfied when the active placement already provides it. With dry_run the same plan is reported without being journaled, so nothing changes. Exact on retry.",
    capability: Capability::Node,
    mutation: true,
    destructive: false,
    result_kind: ResultKind::Mutation,
    max_input_bytes: MAX_INPUT_BYTES,
    wire: WireProfile::V1,
    retry: RetryIdentity::Exact,
    surface: Surface::Administration,
    cli_path: Some("cluster sessions plan"),
    input: InputKind::Literal(
        r#"{"type":"object","additionalProperties":false,"required":["tenant","session","max_failures"],"properties":{"tenant":{"type":"string","minLength":32,"maxLength":32,"pattern":"^[0-9a-f]{32}$"},"session":{"type":"string","minLength":32,"maxLength":32,"pattern":"^[0-9a-f]{32}$"},"survive":{"type":"string","enum":["node","zone","region"]},"max_failures":{"type":"integer","minimum":0,"maximum":255},"dry_run":{"type":"boolean"}}}"#,
    ),
    family: None,
};
pub const ADMIN_TOOL_COUNT: usize = 51;
const ADMIN: [OperationDescriptor; ADMIN_TOOL_COUNT] = [
    CLUSTER_NODE_IDENTITY,
    CLUSTER_NODE_HEALTH,
    CLUSTER_NODE_CONFIG,
    CLUSTER_REPLICAS_DIAGNOSTICS,
    CLUSTER_RETENTION_SHOW,
    CLUSTER_ARCHIVE_SHOW,
    CLUSTER_GC_SHOW,
    CLUSTER_GC_RESTORE,
    CLUSTER_BACKUP_CREATE,
    CLUSTER_BACKUP_VERIFY,
    CLUSTER_RESTORE,
    CLUSTER_STORAGE_SHOW,
    CLUSTER_INVITE,
    CLUSTER_REPLICAS_TRANSFER,
    CLUSTER_REPLICAS_LIST,
    CLUSTER_REPLICAS_SHOW,
    CLUSTER_REPLICAS_ADD_LEARNER,
    CLUSTER_REPLICAS_PROMOTE,
    CLUSTER_REPLICAS_REMOVE,
    CLUSTER_REPLICAS_LEAVE_JOINT,
    CLUSTER_REPLICAS_REQUEST_INSPECT,
    CLUSTER_REPLICAS_REQUEST_RETRY,
    CLUSTER_REPLICAS_REQUEST_RECONCILE,
    CLUSTER_STATUS,
    CLUSTER_MEMBERSHIP_SHOW,
    CLUSTER_NODES_LIST,
    CLUSTER_NODES_DRAIN,
    CLUSTER_NODES_UNDRAIN,
    CLUSTER_NODES_REMOVE,
    CLUSTER_NODES_REPLACE,
    CLUSTER_MEMBERSHIP_ADD_LEARNER,
    CLUSTER_MEMBERSHIP_PROMOTE,
    CLUSTER_MEMBERSHIP_REMOVE,
    CLUSTER_MEMBERSHIP_LEAVE_JOINT,
    CLUSTER_LEADER_TRANSFER,
    CLUSTER_REQUEST_INSPECT,
    CLUSTER_REQUEST_RECONCILE,
    CLUSTER_REQUEST_RETRY,
    CLUSTER_INVITATIONS_LIST,
    CLUSTER_INVITATIONS_GET,
    CLUSTER_CREDENTIALS_GET,
    CLUSTER_INVITATIONS_REVOKE,
    CLUSTER_CREDENTIALS_REVOKE,
    CLUSTER_CREDENTIALS_RENEW,
    CLUSTER_CLIENT_INVITE,
    CLUSTER_PLACEMENT,
    CLUSTER_PLAN,
    CLUSTER_TENANTS_ADMIT,
    CLUSTER_TENANTS_LIST,
    CLUSTER_SESSIONS_CREATE,
    CLUSTER_SESSIONS_PLAN,
];
/// Name order is part of catalogue pagination.
pub fn admin_descriptors() -> &'static [OperationDescriptor] {
    &ADMIN
}
