[package]
name = "focal-log"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
test-support = []

[dependencies]
focal-memory = { version = "0.1.0", path = "../focal-memory" }
crc32fast.workspace = true
fs2.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
