use super::{CliError, Context, Result, args::*, documents::required};
use clap::{Args, Subcommand};
use focal_client::{input::*, operations::*};
use focal_model::MonitorId;
use focal_wire::{Operation, Response};

#[derive(Subcommand)]
pub(crate) enum MonitorCommand {
    /// Register durable predicates for an active claim you issued.
    Register(Box<RegisterArgs>),
    /// Observe the exact committed monitor after a fresh quorum read.
    Get(GetArgs),
}
#[derive(Args)]
pub(crate) struct RegisterArgs {
    #[command(flatten)]
    input: DocumentInput,
    /// Optional exact monitor ID; otherwise saved before first transmission.
    #[arg(long)]
    id: Option<String>,
    /// Active claim for which your authenticated identity is the issuer.
    #[arg(long)]
    owner: Option<String>,
    /// Repeat satisfied:CLAIM_ID, terminal:CLAIM_ID or released:CLAIM_ID.
    #[arg(long = "root")]
    roots: Vec<String>,
    /// Explicit timer identity; no clock or deadline is generated by this command.
    #[arg(long)]
    timer: Option<String>,
    #[arg(long)]
    generation: Option<u64>,
    /// Explicit ledger logical-time deadline (Unix seconds in the node adapter).
    #[arg(long)]
    at: Option<u64>,
    #[command(flatten)]
    mutation: MutationOptions,
}
#[derive(Args)]
pub(crate) struct GetArgs {
    id: String,
    #[command(flatten)]
    output: OutputOptions,
}
pub(super) fn authored(args: RegisterArgs) -> Result<(AuthoredOperation, MutationOptions)> {
    let fields = args.id.is_some()
        || args.owner.is_some()
        || !args.roots.is_empty()
        || args.timer.is_some()
        || args.generation.is_some()
        || args.at.is_some();
    if let Some(document) = args.input.load(fields)? {
        return Ok((AuthoredOperation::MonitorRegister(document), args.mutation));
    }
    if args.roots.len() > focal_wire::MAX_MONITOR_ROOTS {
        return Err(InputError::Capacity.into());
    }
    let mut roots = Vec::new();
    roots
        .try_reserve_exact(args.roots.len())
        .map_err(|_| InputError::Capacity)?;
    for root in args.roots {
        let (predicate, claim) = root.split_once(':').ok_or_else(|| {
            CliError::Input("wait root must be satisfied:ID, terminal:ID or released:ID".into())
        })?;
        roots.push(match predicate {
            "satisfied" => WaitPredicateDocument::Satisfied {
                claim: claim.into(),
            },
            "terminal" => WaitPredicateDocument::Terminal {
                claim: claim.into(),
            },
            "released" => WaitPredicateDocument::Released {
                claim: claim.into(),
            },
            _ => return Err(CliError::Input("unknown wait predicate".into())),
        });
    }
    Ok((
        AuthoredOperation::MonitorRegister(MonitorRegisterDocument {
            monitor: args.id,
            owner: required(args.owner, "owner")?,
            roots,
            deadline: DeadlineDocument {
                timer: required(args.timer, "timer")?,
                generation: required(args.generation, "generation")?,
                at: required(args.at, "at")?,
            },
        }),
        args.mutation,
    ))
}
pub(super) fn get(
    runtime: &tokio::runtime::Runtime,
    context: &Context,
    args: GetArgs,
) -> Result<()> {
    let id = MonitorId(parse_id(&args.id)?);
    let response = runtime.block_on(
        context
            .client
            .request(context.envelope(Operation::Monitor { id })?),
    )?;
    let Response::Monitor(page) = response.result else {
        return Err(CliError::InvalidResponse);
    };
    let missing = page.monitor.is_none();
    match args.output.format {
        OutputFormat::Json | OutputFormat::Yaml => {
            super::output::structured(&page, args.output.format)
        }
        OutputFormat::Table => {
            use std::io::Write;
            let mut out = std::io::stdout().lock();
            writeln!(
                out,
                "MONITOR\t{}\nSEQUENCE\t{}\nROUTE EPOCH\t{}\nAPPLIED INDEX\t{}",
                page.id, page.token.sequence.0, page.token.route_epoch.0, page.applied_index
            )?;
            if let Some(monitor) = page.monitor {
                writeln!(
                    out,
                    "OWNER\t{}\nREGISTERED\t{}\nSTATE\t{}",
                    monitor.owner,
                    monitor.registered.0,
                    if monitor.released.is_some() {
                        "released"
                    } else {
                        "pending"
                    }
                )?;
                if let Some(released) = monitor.released {
                    writeln!(out, "RELEASED SEQUENCE\t{}", released.0)?;
                }
                writeln!(
                    out,
                    "DEADLINE\t{}\nTIMER\t{}\nGENERATION\t{}",
                    monitor.deadline.at, monitor.deadline.timer, monitor.deadline.generation
                )?;
                for root in monitor.roots {
                    writeln!(out, "WAIT\t{root:?}")?;
                }
            } else {
                writeln!(out, "STATE\tmissing")?;
            }
            out.flush()?;
            Ok(())
        }
    }?;
    if missing {
        Err(CliError::NotFound)
    } else {
        Ok(())
    }
}
