[package]
name = "focal-ranges"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
focal-model = { version = "0.1.0", path = "../focal-model" }
focal-memory = { version = "0.1.0", path = "../focal-memory", features = ["serde"] }
serde.workspace = true
postcard.workspace = true
blake3.workspace = true

[lints]
workspace = true
